// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GesCompte.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251209175028_mig3")]
    partial class mig3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Models.Compte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateDeblocage")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Solde")
                        .HasColumnType("numeric");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulaire")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("comptes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 8,
                            DateCreation = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Numero = "SN001",
                            Solde = 510500m,
                            Statut = "Actif",
                            Titulaire = "Ousman Sadjo",
                            Type = "Epargne"
                        },
                        new
                        {
                            Id = 9,
                            DateCreation = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Numero = "SN002",
                            Solde = 50500m,
                            Statut = "Actif",
                            Titulaire = "Layla Sadjo",
                            Type = "Courant"
                        });
                });

            modelBuilder.Entity("Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CompteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Montant")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SoldeApres")
                        .HasColumnType("numeric");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompteId");

                    b.ToTable("transactions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "TRX001",
                            CompteId = 1,
                            Date = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Dépôt cash au guichet",
                            Montant = 150000m,
                            SoldeApres = 150000m,
                            Type = "Depot"
                        },
                        new
                        {
                            Id = 2,
                            Code = "TRX002",
                            CompteId = 1,
                            Date = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Dépôt cash",
                            Montant = 50000m,
                            SoldeApres = 200000m,
                            Type = "Depot"
                        },
                        new
                        {
                            Id = 3,
                            Code = "TRX003",
                            CompteId = 1,
                            Date = new DateTime(2025, 1, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Salaire mensuel",
                            Montant = 120000m,
                            SoldeApres = 320000m,
                            Type = "Depot"
                        },
                        new
                        {
                            Id = 4,
                            Code = "TRX004",
                            CompteId = 1,
                            Date = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Retrait ATM Dakar Plateau",
                            Montant = -20000m,
                            SoldeApres = 300000m,
                            Type = "Retrait"
                        },
                        new
                        {
                            Id = 5,
                            Code = "TRX005",
                            CompteId = 1,
                            Date = new DateTime(2025, 1, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Achat Orange Money",
                            Montant = -15000m,
                            SoldeApres = 285000m,
                            Type = "Retrait"
                        },
                        new
                        {
                            Id = 6,
                            Code = "TRX006",
                            CompteId = 1,
                            Date = new DateTime(2025, 1, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Dépôt wave",
                            Montant = 30000m,
                            SoldeApres = 315000m,
                            Type = "Depot"
                        },
                        new
                        {
                            Id = 7,
                            Code = "TRX007",
                            CompteId = 1,
                            Date = new DateTime(2025, 1, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Paiement Freelance",
                            Montant = 80000m,
                            SoldeApres = 395000m,
                            Type = "Depot"
                        },
                        new
                        {
                            Id = 8,
                            Code = "TRX008",
                            CompteId = 1,
                            Date = new DateTime(2025, 1, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Achat nourriture Auchan",
                            Montant = -25000m,
                            SoldeApres = 370000m,
                            Type = "Retrait"
                        },
                        new
                        {
                            Id = 9,
                            Code = "TRX009",
                            CompteId = 1,
                            Date = new DateTime(2025, 2, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Café Matin",
                            Montant = -5000m,
                            SoldeApres = 365000m,
                            Type = "Retrait"
                        },
                        new
                        {
                            Id = 10,
                            Code = "TRX010",
                            CompteId = 1,
                            Date = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Transport Dem Dikk",
                            Montant = -10000m,
                            SoldeApres = 355000m,
                            Type = "Retrait"
                        });
                });

            modelBuilder.Entity("Models.Transaction", b =>
                {
                    b.HasOne("Models.Compte", "Compte")
                        .WithMany("Transactions")
                        .HasForeignKey("CompteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compte");
                });

            modelBuilder.Entity("Models.Compte", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
